name: BedrockGUI-EssentialsAddon
version: '${version}'
main: it.pintux.life.essentialsaddon.BedrockEssentialsAddonPlugin
api-version: '1.19'
author: 'pintux'
depend:
  - BedrockGUI
softdepend:
  - Essentials
  - CMI
  - ShopGUIPlus
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - HuskHomes
  - MyPet
commands:
  essentialsaddon:
    description: Reload EssentialsAddon configuration
    usage: /essentialsaddon reload
    permission: essentialsaddon.reload
  pet:
    description: Open the Bedrock pet menu
    usage: /pet
    aliases: [pets]
