name: BedrockGUI-BedwarsAddon
version: '${version}'
main: it.pintux.life.bedwarsaddon.BedrockBedwarsAddonPlugin
api-version: '1.20'
author: pintux
depend:
  - BedrockGUI
softdepend: [BedWars2023, floodgate]
commands:
  bedwarsaddon:
    description: Bedwars addon admin command
    usage: /bedwarsaddon reload
    aliases: [bwaddon]
