assets:
  enabled: false
  port: 0
  host: ""

forms:
  main_menu:
    file: "main_menu.yml"
  button_images:
    file: "button_images.yml"
  basic_actions:
    file: "basic_actions.yml"
  economy_shop:
    file: "economy_shop.yml"
  player_settings:
    file: "player_settings.yml"
  confirm_reset:
    file: "confirm_reset.yml"
  advanced_flow:
    file: "advanced_flow.yml"
