name: BedrockGUI-Paper
version: '${version}'
main: it.pintux.life.paper.BedrockGUI
api-version: '1.19'
folia-supported: true
author: "pintux"
depend:
  - floodgate
softdepend:
  - PlaceholderAPI
  - Vault
  - LuckPerms
commands:
  bedrockgui:
    usage: "/bedrockgui <reload | open | openfor>"
    permission: "bedrockgui.admin"
    aliases:
      - "bgui"


